version: "3.4"

services:

  jenkins:
    image: jenkins/jenkins
    restart: unless-stopped
    ports:
      - "8000:8080"
    environment:
      - JAVA_OPTS:-Djava.awt.headless=true
    networks:
      - sonarnet
    volumes:
      - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9092:9092"
    depends_on:
      - "db"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=v07IGCFCF83Z95NX
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  db:
    image: postgres
    restart: unless-stopped
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=v07IGCFCF83Z95NX
      - POSTGRES_DB=sonarqube
    expose:
      - "5462"
    ports:
      - "5462:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
  jenkins_home:
